version: '3.8'

services:
  # Backend API - Producción
  api:
    build:
      context: .
      target: production
    ports:
      - "${API_PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongodb
    volumes:
      - ${UPLOAD_PATH}:/app/uploads
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT}/apidoc"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Backend API - Desarrollo
  api-dev:
    build:
      context: .
      target: development
    ports:
      - "${API_DEV_PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
      - ${UPLOAD_PATH}:/app/uploads
    networks:
      - app-network
    restart: unless-stopped
    command: ["npm", "run", "start:dev"]

  # Base de datos MongoDB
  mongodb:
    image: mongo:7.0
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Interfaz web para MongoDB (opcional)
  mongo-express:
    image: mongo-express:latest
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
